chore(utils): migrate to picocolors
vuepress/vuepress-next pull request #1145
Opened 2022-10-25 00:29 UTC by azat-io

`picocolors` 14 times smaller and 2 times faster than `chalk`.

VitePress also use `picocolors`:
https://github.com/vuejs/vitepress/pull/659

2022-10-27 08:56 UTC, meteorlxy requested changes
Should use a shorter name or even replace `chalk` directly

2022-10-27 09:00 UTC, Mister-Hope commented
Just as a reminder: This will be a breaking change. As most of my plugins are using chalk imported from `@vuepress/utils` to print logs in terminal.

2022-10-27 12:46 UTC, azat-io commented
> I think we should re-export `picocolors` to something shorter (like `colors` or even `chalk`)

Renamed to `colors`

> Just as a reminder: This will be a breaking change. As most of my plugins are using chalk imported from `@vuepress/utils` to print logs in terminal.
> 
> So AT LEAST it should NOT be marked as `chore`

Updated PR type to `feat`

2022-10-28 07:00 UTC, meteorlxy approved these changes

2022-10-28 07:02 UTC, merged