fix: fix missing deps and build order
vuepress/vuepress-next pull request #160
Opened 2021-05-23 10:01 UTC by xinpingwang

1. some package used in source code, but not listed in `package.json`

| repo dir  | missing deps | used in |
| -- | -- | -- |
| @vuepress/client | vite | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/client/tsconfig.json#L22 |
| @vuepress/plugin-docsearch | @docsearch/react | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-docsearch/src/shared/types.ts#L1 |
| @vuepress/plugin-pwa-popup | vue | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-pwa-popup/src/client/components/PwaPopup.ts#L1 |
| @vuepress/plugin-search | vite | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-search/tsconfig.json#L9 |
| @vuepress/plugin-theme-data | vite, vue | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-theme-data/tsconfig.json#L9 https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-theme-data/src/client/clientAppEnhance.ts#L1 |
| @vuepress/plugin-toc | vue-router | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-toc/src/client/components/Toc.ts#L4 |
| @vuepress/theme-vue | @vuepress/core | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/theme-vue/src/node/vueTheme.ts#L1 |

2. ts build order: 

`@vuepress/theme-vue` deps on `@vuepress/core`, thus `@vuepress/core` should build first

2021-05-23 10:08 UTC, nsznsznjsz commented
I think `@vuepress/client` should not depend on `vite`

2021-05-23 10:34 UTC, xinpingwang commented
> I personally think `@vuepress/client` should not depend on `vite`

Vite exposes its manual HMR API via the special `import.meta.hot` object, and declare it at `vite/client.d.ts`. `@vuepress/client` using it to avoid ts build error, so at least `vite` should be an devDependencies, i will change it, and others. 😁

2021-05-23 11:16 UTC, meteorlxy commented
Nice catch. Then `@types/webpack-env` should go along with `vite`.

---

I've noticed that we are missing deps. I'll update the eslint rules later to check the dependencies.

2021-05-23 11:44 UTC, xinpingwang commented
> Nice catch. Then `@types/webpack-env` should go along with `vite`.

Updated，😄

2021-05-24 10:13 UTC, meteorlxy requested changes

2021-05-24 10:13 UTC, meteorlxy commented on packages/@vuepress/plugin-docsearch/package.json
> +    "@docsearch/react": "3.0.0-alpha.34"
This one should be put into `dependencies`

2021-05-24 10:13 UTC, meteorlxy commented on packages/@vuepress/theme-vue/package.json
> +    "@vuepress/core": "2.0.0-beta.14"
This one should be put into `dependencies`

2021-05-24 13:00 UTC, xinpingwang commented
@meteorlxy thanks for your review, changed.

2021-05-24 16:51 UTC, meteorlxy approved these changes
LGTM

2021-05-24 16:59 UTC, merged