feat(theme-default): improve darkmode button a11y
vuepress/vuepress-next pull request #275
Opened 2021-07-10 02:28 UTC by Mister-Hope

2021-07-10 02:29 UTC, Mister-Hope commented
This should fix #270

2021-07-10 15:11 UTC, meteorlxy requested changes
And the docs should be updated, too.

2021-07-10 15:11 UTC, meteorlxy commented on packages/@vuepress/theme-default/src/shared/options.ts
> +  darkmodeText?: string
Should use the same camelCase as the `darkMode` option

2021-07-10 15:11 UTC, meteorlxy commented on packages/@vuepress/theme-default/src/client/components/ToggleDarkModeButton.vue
> +  const themeLocale = useThemeLocaleData()
Put the `use` function outside computed

2021-07-10 15:11 UTC, meteorlxy commented on packages/@vuepress/theme-default/src/client/components/ToggleDarkModeButton.vue
> +  const themeLocale = useThemeLocaleData()
In fact, we may not need a computed value here. We should set the default value in `assignDefaultLocaleOptions`

2021-07-11 07:08 UTC, Mister-Hope commented
Just find out I format the rest of the docs when saving, but I think that's fine, if you refuse it I will revert and recommit the docs changes.

2021-07-12 12:20 UTC, meteorlxy commented on packages/@vuepress/theme-default/src/client/components/ToggleDarkModeButton.vue
> +    @click="themeLocale.darkModeText"
... I think you should test PR locally first 😅

2021-07-12 13:42 UTC, merged

2021-07-12 16:27 UTC, Mister-Hope commented
My fault, I tested before opening it, but I am lazy testing it after a refactor 🌚