feat: add sitemap plugin
vuepress/vuepress-next pull request #277
Opened 2021-07-10 04:14 UTC by Mister-Hope

2021-07-10 07:35 UTC, Mister-Hope commented
Addtional: CI failed because of coverage, but since this plugin is deeply coupled with vuepress plugin api, it's hard to add some tests.

2021-07-10 15:20 UTC, meteorlxy requested changes
Follow the same file structure as other plugins, i.e. only use `node/index.ts` to import/export things, and use a `node/sitemapPlugin.ts` file to declare the plugin

2021-07-10 15:20 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/src/node/index.ts
> +  const hostname = options.hostname || (themeConfig.hostname as string)
We should avoid reading themeConfig in plugins

2021-07-19 17:07 UTC, meteorlxy requested changes

2021-07-19 17:07 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +- Required: Yes
Required: `true` / `false`

Be consistent with other docs

2021-07-19 17:07 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +- Default value: `"sitemap.xml"`
- Default:

2021-07-19 17:07 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/package.json
> +  "devDependencies": {},
remove

2021-07-19 17:07 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/src/node/generateSitemap.ts
> +  /** path of '/' */
Use `//` for single line comments

2021-07-19 17:07 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/src/node/types/frontmatter.ts
> +   * 更新频率
Remove zh comments

2021-08-01 10:51 UTC, Mister-Hope commented
Got it. i will update these days!

2021-08-03 06:49 UTC, ramesh-dada commented
@meteorlxy @Mister-Hope THANK You so much for doing great work is their any estimated release date that when this plugin will be released ?

2021-08-05 09:24 UTC, Mister-Hope commented
I am finishing all the changes, except I remain zh jsdocs in `SitemapOptions`.

IMO, as we are providing both chinese and english docs, it's reasonable to keep bothe languages in the final options provided to users to make sure they get full hints.

2021-08-05 09:35 UTC, meteorlxy requested changes

2021-08-05 09:35 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/package.json
> +    "chalk": "^4.1.1",
`chalk` is also included in `@vuepress/utils`

2021-08-05 09:35 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/package.json
> +    "@vuepress/utils": "2.0.0-beta.21",
Sync the version

2021-08-05 09:35 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/src/node/types/options.ts
> +  /** XML namespaces to turn on - all by default */
Keep the comment style consistent

2021-08-05 09:35 UTC, meteorlxy commented on yarn.lock
> +
Should not be committed

2021-08-05 09:35 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  Page default update frequency
Missing ending period

2021-08-05 09:35 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  Page priority, range from 0 - 1
```suggestion
  Page priority, range from `0` to `1`.
```

2021-08-05 09:36 UTC, meteorlxy commented
> IMO, as we are providing both chinese and english docs, it's reasonable to keep both the languages in the final options provided to users to make sure they get full hints.

Remove them, or we need to add translations to all other comments.

2021-08-06 02:39 UTC, maodou38 commented
it's happy to know that we will support support sitemap recently.And also appreciate @Mister-Hope ‘s sitemap plugin.
i will use your plugin until the official release version online

2021-08-08 05:34 UTC, ramesh-dada commented
@Mister-Hope Before you merge this can you please take a look at this also https://github.com/vuepress/vuepress-next/issues/353

2021-08-14 07:48 UTC, Mister-Hope commented
I would prefer not to support any of the 2 fr in #353.  For my personal reason, see https://github.com/vuepress/vuepress-next/issues/353#issuecomment-898859697

If you have different ideas and think any of them should be supported, just leave a message.

2021-08-14 09:54 UTC, meteorlxy requested changes

2021-08-14 09:54 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/src/node/types/sitemap.ts
> +  /** The URL of the image. */
Normalize comment format

2021-08-14 09:54 UTC, meteorlxy commented on yarn.lock
> +
Run `npx yarn-deduplicate` to reduce duplicated lock records

2021-08-14 09:54 UTC, meteorlxy commented on docs/zh/reference/plugin/sitemap.md
> +  页面默认更新频率
缺少句号，下同

2021-08-25 02:40 UTC, maodou38 commented
why the pull request bog down？

2021-10-05 02:23 UTC, liziwl commented
Any progress on the feature of sitemap?

2021-12-09 21:38 UTC, KnorpelSenf commented
What are the chances that this lands in the 2.0 release?

2021-12-31 15:36 UTC, jrcharles commented
Any update here?

2022-01-04 06:46 UTC, Mister-Hope commented
I will finish it once my winter vacation begins, just busy being a postgraduate student studying quantum physics

2022-01-09 06:06 UTC, Mister-Hope commented
@meteorlxy Should be ready

2022-01-12 07:36 UTC, meteorlxy requested changes

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +- Type: `'always'|'hourly'|'daily'|'weekly'|'monthly'|'yearly'|'never'`
Spaces around `|`

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +## Frontmatter Options
Consistent with docs of other plugin.

`Frontmatter Options` -> `Frontmatter`

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +## Plugin options
Consistent with docs of other plugin.

`Plugin options` -> `Options`

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  The output filename.
More description about the filename, is it relative to dest or somewhere?

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +### outFile
What about `outputFile`? Or using `sitemapFilename` like PWA plugin does?

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  Page default update frequency.
More description about the differences between frontmatter and options, i.e. should specify that frontmatter would override options in current page.

Also, should add reference to corresponding options, and vice versa.

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  Pages not included.
Need more detailed explanation. 

- File path or route path?
- Relative path or absolute path?

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  Time formatter. The timestamp will be automatically generated through git plugin by default.
Why a time / date formatter accepting a `page` arg ? Consider renaming it to `dateGetter` or so.

Also, it's better to provide an example.

2022-01-12 07:36 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +- Required: false
Wrap false with backticks

2022-01-12 07:36 UTC, meteorlxy commented on packages/@vuepress/plugin-sitemap/tsconfig.build.json
> +  ]
plugin-git

2022-01-15 14:32 UTC, Mister-Hope commented
Some explaination:

- A lot of plugin option has been renamed
- `modifyTimeGetter` is better with a `Page` arg, see plugin docs example
- A short description of sitemap is added.

2022-01-18 09:12 UTC, meteorlxy requested changes

2022-01-18 09:12 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +- Required: true
backtick

2022-01-18 09:12 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +### extraURLs
Should be `extraUrls` ?

2022-01-18 09:12 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +### excludePages
Should be `excludeUrls`?

2022-01-18 09:12 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +  ```
Remove the indents of code block

2022-01-18 09:12 UTC, meteorlxy commented on docs/reference/plugin/sitemap.md
> +For use by search engines and other crawlers, there is a structured format, the XML Sitemap, which lists the pages in a site, their relative importance, and how often they are updated. This is pointe
English and Chinese version is inconsistent 🤔

2022-01-21 07:29 UTC, Zhengqbbb commented
@Mister-Hope Hi
Just used it today. The feeling is the same as imagined, very good feeling, but at the same time there are problems and bugs.

1. The `priority` configuration item in the document, (docs/zh/reference/plugin/sitemap.md: 85).Until I found that there is no SitemapOptions type, it means that **the configuration will not take effect**.This is very good design for normal pages.
2. About `robots.txt` generate options. see: https://developers.google.com/search/docs/advanced/robots/robots_txt
3. The `excludeUrls` default option not work. If I don't add the option manually, the 404 page will not be excluded
![image](https://user-images.githubusercontent.com/40693636/150484514-ee4ce780-4d4c-4c8b-aaaf-92b61127a2e8.png)
4. The `exclude`Frontmatter not work until I configured `excludeUrls` option.

2022-01-21 10:17 UTC, Mister-Hope commented
> @Mister-Hope Hi Just used it today. The feeling is the same as imagined, very good feeling, but at the same time there are problems and bugs.
> 
> 1. The `priority` configuration item in the document, (docs/zh/reference/plugin/sitemap.md: 85).Until I found that there is no SitemapOptions type, it means that **the configuration will not take effect**.This is very good design for normal pages.
> 2. About `robots.txt` generate options. see: https://developers.google.com/search/docs/advanced/robots/robots_txt
> 3. The `excludeUrls` default option not work. If I don't add the option manually, the 404 page will not be excluded
>    ![image](https://user-images.githubusercontent.com/40693636/150484514-ee4ce780-4d4c-4c8b-aaaf-92b61127a2e8.png)
> 4. The `exclude`Frontmatter not work until I configured `excludeUrls` option.

Hi, thanks for the feed back, I will have a look later on 1,3,4 , but I am not catching what you mean about 2. All the output folder is deployed directly, so if user set a base, there is no way for me to generate a robot.txt and place outside the dest folder. The robots.txt should be ignored by google. Also, I am not sure all the search engine won't read subfolder robot.txt. Besides, a sitemap plugin should not try to set `allow` and `disallow` for developers, in my case, I am having a valid robot.txt in my project public folder, and I only want the plugin appends sitemap link for me. If you have any idea (which is better), please point it out since I have no idea how to improve it now.

2022-01-21 11:43 UTC, Zhengqbbb commented
> > @Mister-Hope 
> Hi, thanks for the feed back, I will have a look later on 1,3,4 , but I am not catching what you mean about 2. All the output folder is deployed directly, so if user set a base, there is no way for me to generate a robot.txt and place outside the dest folder. The robots.txt should be ignored by google. Also, I am not sure all the search engine won't read subfolder robot.txt. Besides, a sitemap plugin should not try to set `allow` and `disallow` for developers, in my case, I am having a valid robot.txt in my project public folder, and I only want the plugin appends sitemap link for me. If you have any idea (which is better), please point it out since I have no idea how to improve it now.

ok, I just think that if there is automatic generate robots.txt, it is better to have a better place to configure.
Maybe someone needs to disable the search spider to crawl their own website to prevent it from being website included, such as only for Google Spider, we can provide option to set user-agent.
If you want to uniformly set recommended website inclusion and non-recommended website inclusion, you need Allow and Disallow.

2022-01-22 02:38 UTC, Mister-Hope commented
I will change the logic, only when base is `/` and user has a robot.txt in public folder, the plugin will try to add sitemap url to it. This should be better.

2022-01-22 02:41 UTC, Mister-Hope commented
And for 1, you should set priority in `frontmatter.sitemap.priority` and it's injected in the speard operator I think.

```
    const sitemapInfo: SitemapPageInfo = {
      changefreq,
      links,
      ...(lastmodifyTime ? { lastmod: lastmodifyTime } : {}),
      ...frontmatterOptions,
    }
```

Is this option problematic to you?

2022-01-22 02:51 UTC, Mister-Hope commented
The missing line in https://github.com/vuepress/vuepress-next/pull/277/commits/f043211d2cea84c83396cf1f91c1123fa4b7d22a should solve both 3 and 4 @Zhengqbbb Thanks for point out the bug.

2022-01-22 08:57 UTC, Zhengqbbb commented
> I will change the logic, only when base is `/` and user has a robot.txt in public folder, the plugin will try to add sitemap url to it. This should be better.

I also think this is the right design, **whatever this is a sitemap plugin**. 
But robot.txt is spider friendly for sites that don't submit sitemaps. **For documentation**, it would be better to mention that robot.txt needs to be added to the publish folder.

2022-01-22 09:04 UTC, Zhengqbbb commented
> And for 1, you should set priority in `frontmatter.sitemap.priority` and it's injected in the speard operator I think.
> Is this option problematic to you?

- But you can see that **it is not mentioned in the English document**, but mentioned in the one asked in Chinese.
- I think the significance of this option item is that for `md ` files that do not declare formatter on normal pages, this is a **unified** source of priority. After all, everyone is not very willing to think about the priority of this page.

2022-01-22 09:05 UTC, Zhengqbbb commented
> > And for 1, you should set priority in `frontmatter.sitemap.priority` and it's injected in the speard operator I think.
> > Is this option problematic to you?
> 
> * But you can see that **it is not mentioned in the English document**, but mentioned in Chinese document.
> * I think the significance of this option item is that for `md ` files that do not declare formatter on normal pages, this is a **unified** source of priority. After all, everyone is not very willing to think about the priority of this page.

2022-01-31 09:20 UTC, Mister-Hope commented
> 

The missing option in docs is added.

2022-01-31 09:21 UTC, Mister-Hope commented
> > And for 1, you should set priority in `frontmatter.sitemap.priority` and it's injected in the speard operator I think.
> > Is this option problematic to you?
> 
> * But you can see that **it is not mentioned in the English document**, but mentioned in the one asked in Chinese.
> * I think the significance of this option item is that for `md ` files that do not declare formatter on normal pages, this is a **unified** source of priority. After all, everyone is not very willing to think about the priority of this page.

A description is added

2022-01-31 09:21 UTC, Mister-Hope commented
@meteorlxy Could you have another check?

2022-02-09 08:12 UTC, Jelledb commented
Looking forward to the sitemap plugin!

2022-02-28 13:32 UTC, JohannesRudolph commented
I can confirm the sitemap plugin is working fine, pulled the code from the PR in as a "vendored" dependency and it works great for our site.

2022-03-31 16:13 UTC, JohannesRudolph commented
One feedback, I'd like to have the option to set the `changefreq` option to null/undefined so that it's not part of the sitemap. Since we already have `lastmod` this is going to be fine for most sites and sends less confusing signals to search engine crawlers.

2022-05-04 21:45 UTC, hustcer commented
It's really a long time to wait

2022-05-06 03:56 UTC, Mister-Hope commented
You can use `vuepress-plugin-sitemap2`

2022-09-04 19:35 UTC, Zhengqbbb commented
> Any updates?
> 
> Also, I found this site helpful:
> 
> https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap

Hey u can use `vuepress-plugin-sitemap2`
Demo:
https://github.com/Zhengqbbb/vuepress-plugin/blob/b5383fa7d8a548d8306f5ab49e60a4a567281874/docs/.vuepress/config.ts#L42-L45

2022-09-05 05:21 UTC, Mister-Hope commented
That plugin is published by me as the same with this pr.

2022-12-09 02:18 UTC, taozuhong commented
能不能早点合入并发布稳定版本？要不 VitePress 都出来了，它的价值空间就会被严重挤压，这么多努力就白费了。

2022-12-09 03:59 UTC, meteorlxy commented
@taozuhong You can take a look at https://github.com/vuejs/vitepress/discussions/548

VitePress might be VuePress 3 as a decision of Vue.js Team. So VuePress 2 has already been in an awkward position. That's why the stable version delayed a lot.

2022-12-09 05:41 UTC, Mister-Hope commented
I am updating `vuepress-plugin-sitemap2` with every vp2 version, you are free to use that.

2022-12-09 06:19 UTC, taozuhong commented
> @taozuhong You can take a look at [vuejs/vitepress#548](https://github.com/vuejs/vitepress/discussions/548)
> 
> VitePress might be VuePress 3 as a decision of Vue.js Team. So VuePress 2 has already been in an awkward position. That's why the stable version delayed a lot.

Nice to see it, hope the plugins Api become more stable than last, make the plugin ecosystem release more power.

2023-01-31 18:37 UTC, Mister-Hope commented
Closing, this will be maintained speratedly

2023-01-31 18:37 UTC, closed without merging