docs: update extending-a-theme.md
vuepress/vuepress-next pull request #326
Opened 2021-08-01 13:45 UTC by jiazengp

See ([a8de0a9](https://github.com/vuepress/vuepress-next/commit/a8de0a990711a2732f2f85b086e733fbd8a74110))

2021-08-01 13:55 UTC, meteorlxy requested changes

2021-08-01 13:55 UTC, meteorlxy commented on docs/advanced/cookbook/extending-a-theme.md
> +- `page`
Let's put `page` before `page-top`

2021-08-01 16:05 UTC, jiazengp commented on docs/advanced/cookbook/extending-a-theme.md
> +- `page`
All right

2021-08-02 08:00 UTC, meteorlxy approved these changes

2021-08-02 08:01 UTC, merged