feat(theme-default): add heroImageDark https://github.com/vuepress/vu…
vuepress/vuepress-next pull request #559
Opened 2021-12-10 11:51 UTC by qcyblm

…epress-next/issues/526

2021-12-10 18:54 UTC, alirezanet commented on packages/@vuepress/theme-default/src/client/components/Home.vue
> +    return frontmatter.value.heroImageDark
I think you should use withBase, 
``` ts
const heroImage = computed(() => {
  if (frontmatter.value.heroImageDark && isDarkMode.value) {
    return withBase(frontmatter.value.heroImageDark)
  }
  if (frontmatter.value.heroImage) {
    return withBase(frontmatter.value.heroImage)
  }
  return null
})
```

2021-12-11 05:13 UTC, qcyblm commented on packages/@vuepress/theme-default/src/client/components/Home.vue
> +    return frontmatter.value.heroImageDark
```
<img v-if="heroImage" :src="withBase(heroImage)" :alt="heroAlt" />
```

2021-12-14 08:25 UTC, alirezanet commented
any update on this? :(
you can find a real-world example [here](https://alirezanet.github.io/Gridify/) why we need this

2021-12-15 08:44 UTC, meteorlxy requested changes

2021-12-15 08:44 UTC, meteorlxy commented on packages/@vuepress/theme-default/src/client/components/Home.vue
> +      <img v-if="heroImage" :src="withBase(heroImage)" :alt="heroAlt" />
Also need to wrap the image with `<ClientOnly>`

2021-12-17 04:37 UTC, meteorlxy approved these changes
LGTM

2021-12-17 05:01 UTC, merged