feat: centered up and down title when no content in custom container
vuepress/vuepress-next pull request #657
Opened 2022-01-26 05:00 UTC by zh-lx

fixed #648 
When there's no content in custom container, the title of custom container is not centered up and down, and the reason is that `margin-bottom: -0.4em;` overwrites the original `margin-bottom` of the `p` tag. So removing this style ensures that the title is center when no content in custom container. In addition, the container is not affected when it has content.

style of container without content:
![image](https://user-images.githubusercontent.com/73059627/151106468-75c83045-ebe0-4f05-a140-5d977fdcbfd8.png)

style of container with content:
![image](https://user-images.githubusercontent.com/73059627/151106527-2d0069e1-c16b-47af-bb9e-4b722db98e98.png)

2022-02-10 07:14 UTC, meteorlxy commented
The style will be slightly different without the offset. You'd better keep it consistent.

2022-02-14 14:41 UTC, Mister-Hope requested changes

2022-02-14 14:41 UTC, Mister-Hope commented on packages/@vuepress/theme-default/src/client/styles/custom-container.scss
>    }
```suggestion
    &:not(:only-child) {
      margin-bottom: -0.4rem;
    }
  }
```

2022-02-16 08:31 UTC, Mister-Hope approved these changes

2022-02-16 08:43 UTC, meteorlxy approved these changes

2022-02-16 08:44 UTC, merged