Added themeConfig access to the v2 migration guide
vuepress/vuepress-next pull request #687
Opened 2022-02-11 14:23 UTC by ArsalaBangash

@Mister-Hope recommended adding docs about themeConfig access to the v2 migration guide after he answered [this question](https://github.com/vuepress/vuepress-next/discussions/686)

2022-02-11 15:11 UTC, Mister-Hope requested changes

2022-02-11 15:11 UTC, Mister-Hope commented on docs/guide/migration.md
> -- Markdown code blocks syntax highlighting by Prism.js is not embedded by default. You can use either [@vuepress/plugin-prismjs](../reference/plugin/prismjs.md) or [@vuepress/plugin-shiki](../referen
I think `embedded` is better, Meteorlxy is trying to express we are extracting code higlight feature as plugins from `@vuepress/markdown` (the markdown render) here.

2022-02-11 15:11 UTC, Mister-Hope commented on docs/guide/migration.md
> +- To access the themeConfig as you would via `this.$site.themeConfig` in v1, we now recommend using the [@vuepress/plugin-theme-data](../reference/plugin/theme-data.md) plugin and it's useThemeData c
Please add the below line to zh docs.

如果你想要在主题中访问 themeConfig，我们现在建议使用 [@vuepress/plugin-theme-data](../reference/plugin/theme-data.md) 插件和它提供的 Composition API `useThemeData`

2022-02-11 15:11 UTC, Mister-Hope commented on docs/guide/migration.md
> +- To access the themeConfig as you would via `this.$site.themeConfig` in v1, we now recommend using the [@vuepress/plugin-theme-data](../reference/plugin/theme-data.md) plugin and it's useThemeData c
```suggestion
- To access the themeConfig as you would via `this.$site.themeConfig` in v1, we now recommend using the [@vuepress/plugin-theme-data](../reference/plugin/theme-data.md) plugin and it's `useThemeData` compoition function
```

2022-02-17 14:51 UTC, meteorlxy requested changes

2022-02-24 09:05 UTC, merged

2022-02-24 09:05 UTC, meteorlxy commented
@ArsalaBangash Thanks for the contribution! ❤️