build: drop support for node 12
vuepress/vuepress-next pull request #852
Opened 2022-04-27 15:16 UTC by Mister-Hope

BREAKING CHANGES: node 12 is dropped

2022-04-27 15:17 UTC, Mister-Hope commented
Node 12 will end up LTS support in 2022/5/1, and target: es2020 is aligning with minimal node 14 support.

This helps generating code with less polyfills.

2022-04-27 16:13 UTC, meteorlxy requested changes
As commented above

2022-04-28 03:45 UTC, meteorlxy requested changes

2022-04-28 03:45 UTC, meteorlxy commented on docs/guide/deployment.md
> +          node-version: '16'
No need to change the deployment guide. Use the lowest LTS version is OK here. (We should use 12 before :sweat_smile:)

2022-05-01 13:15 UTC, meteorlxy approved these changes

2022-05-01 13:17 UTC, merged