docs: add pnpm docs
vuepress/vuepress-next pull request #929
Opened 2022-06-06 11:01 UTC by Mister-Hope

2022-06-06 13:08 UTC, meteorlxy commented on docs/README.md
> +pnpm add -D vue @vuepress/client@nextvuepress@next
- put vuepress first
- missing whitespace

2022-06-06 13:09 UTC, meteorlxy commented on docs/guide/deployment.md
> +        uses: actions/cache@v3
Remove cache action, and use `cache` option of setup-node action

2022-06-06 13:10 UTC, meteorlxy commented on docs/guide/getting-started.md
> +pnpm add -D vue @vuepress/client@next vuepress@next
Same here

2022-06-07 02:00 UTC, meteorlxy requested changes

2022-06-07 02:00 UTC, meteorlxy commented on docs/guide/deployment.md
> +
Avoid this kind of formatting (and below)

2022-10-19 01:50 UTC, Mister-Hope commented on docs/zh/guide/deployment.md
> +          version: 7
```suggestion
          version: 8
```

2022-10-19 01:50 UTC, Mister-Hope commented on docs/guide/deployment.md
> +          version: 7
```suggestion
          version: 8
```

2022-10-24 00:10 UTC, azat-io commented
Might be worth merge it?

2022-11-07 04:40 UTC, Mister-Hope commented on docs/guide/deployment.md
> +          node-version: 16
```suggestion
          node-version: 18
```

2022-11-07 04:40 UTC, Mister-Hope commented on docs/guide/deployment.md
> +          version: 8
```suggestion
          version: 7
```

2022-11-07 04:40 UTC, Mister-Hope commented on docs/guide/deployment.md
> +          node-version: '14'
```suggestion
          node-version: 18
```

2022-11-07 04:40 UTC, Mister-Hope commented on docs/zh/guide/deployment.md
> +          node-version: 16
```suggestion
          node-version: 18
```

2022-11-07 04:40 UTC, Mister-Hope commented on docs/zh/guide/deployment.md
> +          version: 8
```suggestion
          version: 7
```

2022-11-07 04:40 UTC, Mister-Hope commented on docs/zh/guide/deployment.md
> +          node-version: '14'
```suggestion
          node-version: 18
```

2022-11-07 04:41 UTC, Mister-Hope commented
> Might be worth merge it?
> 
> **upd.** I think the order should be: npm, pnpm, yarn. This seems more logical.

pnpm takes less time during install comparing to npm. so we do recommand people to use pnpm as first choise.

2022-12-06 03:27 UTC, meteorlxy commented
We may also need to update the deployment guide to use pnpm as recommendation

2022-12-07 11:56 UTC, Mister-Hope commented
Done @meteorlxy

2022-12-07 17:19 UTC, meteorlxy commented on docs/guide/deployment.md
> +  <CodeGroupItem title="YARN">
We could remove the yarn tab then, as we are assuming user is using pnpm

2022-12-07 17:20 UTC, meteorlxy commented on docs/guide/deployment.md
> +   - **BUILD COMMAND:** `yarn docs:build`
pnpm

2022-12-07 17:20 UTC, meteorlxy commented on docs/zh/guide/deployment.md
> +  <CodeGroupItem title="YARN">
Same here

2022-12-07 17:21 UTC, meteorlxy commented on docs/zh/guide/deployment.md
> +   - **Build Command:** `yarn docs:build`
Same here

2022-12-08 10:06 UTC, meteorlxy requested changes

2022-12-08 10:06 UTC, meteorlxy commented on docs/guide/deployment.md
> +   - **Build Command:** `npm i -g pnpm@7 && pnpm docs:build`
Is it necessary to add `@7` for pnpm? If not, we'd better remove it so we don't need to update it in the future

2022-12-08 10:06 UTC, meteorlxy commented on docs/zh/guide/deployment.md
> +3. 在执行了 `pnpm docs:build`, `yarn docs:build` 或 `npm run docs:build` 后, 使用 `firebase deploy` 指令来部署。
Same here

2022-12-08 10:06 UTC, meteorlxy commented on docs/zh/guide/deployment.md
> +   - **Build Command:** `npm i -g pnpm@7 && pnpm docs:build`
Same here

2022-12-08 13:22 UTC, merged